version: "{build}"

image: Visual Studio 2015

clone_depth: 100

clone_folder: c:\projects\python-gammu


environment:
  global:
    PYTHON_ARCH: "32"
    GAMMU_VERSION: "1.38.4"
    GAMMU_PATH: "C:\\Gammu"
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.1"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.3"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  #  Install Gammu
#  - appveyor DownloadFile https://dl.cihar.com/gammu/releases/windows/Gammu-%GAMMU_VERSION%-Windows.exe
  - appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/msk3l7g5lli5b733/artifacts/Gammu-1.38.4-Windows.exe
  - Gammu-%GAMMU_VERSION%-Windows.exe /S /D=%GAMMU_PATH%
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

build_script:
  # Build the compiled extension
  - "python setup.py build"

test_script:
  # Run the project tests
- "python setup.py test"


after_test:
  # If tests are successful, create binary packages for the project.
  - "python setup.py bdist_wheel"
  - "python setup.py bdist_wininst"
  - "python setup.py bdist_msi"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
